name: Android Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Use Java 17 (Temurin) instead of Java 11
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Install the SDK with the components in one block
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: |
            platform-tools
            platforms;android-33
            build-tools;33.0.0

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
