name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # 3) Set up the Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.0'
          components: |
            platforms;android-33
            build-tools;33.0.0
            platform-tools

      # 4) Grant gradlew the right to execute, then build in release mode
      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 5) Upload the generated .apk as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
